name: Release on push to main
on:
  push:
    branches:
      - main
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
